//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShop.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID { get; set; }
        public int ProductArticleID { get; set; }
        public int NameCategoryID { get; set; }
        public string Unit { get; set; }
        public decimal ProductCost { get; set; }
        public int MaxDiscount { get; set; }
        public int ManufacturerID { get; set; }
        public int DealerID { get; set; }
        public int ProductCategoryID { get; set; }
        public int ProductDiscount { get; set; }
        public int ProductQuantityInStock { get; set; }
        public string ProductDescription { get; set; }
        public string ProductPictureName { get; set; }
        public byte[] ProductPicture { get; set; }
    
        public virtual Dealer Dealer { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual NameCategory NameCategory { get; set; }
        public virtual ProductArticle ProductArticle { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
    }
}
